name: React CI-CD Pipeline

on: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test-React:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Code
        uses: actions/checkout@v4

      - name: Node-Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm i

      - name: Create Build
        run: npm run deploy
